### ISSUE TITLE
No ratelimit support.

### ISSUE THREAD

**Issue by macdja38** [BrightSkyz/DisHTML#1]
I think this library shows a lot of promise, but... ~~the fact that it doesn't actually do anything really let me down. I'm hoping this issue can be resolved soon. Also proper~~ rate-limit support would be nice, thanks!

**Comment by BrightSkyz** [comment]
Will start work on rate-limiting ASAP. Hopefully will be ready soon!

**Comment by BrightSkyz** [comment]
Ratelimit support added.
-Issue Closed-
